apiVersion: misconf.controller.anaisurl.com/v1
kind: MisconfController
metadata:
  labels:
    app.kubernetes.io/name: misconfcontroller
    app.kubernetes.io/instance: misconfcontroller-sample
    app.kubernetes.io/part-of: controller
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: controller
  name: misconfcontroller-sample
spec:
  # TODO(user): Add fields here
