# permissions for end users to view misconfcontrollers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: misconfcontroller-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: controller
    app.kubernetes.io/part-of: controller
    app.kubernetes.io/managed-by: kustomize
  name: misconfcontroller-viewer-role
rules:
- apiGroups:
  - misconf.controller.anaisurl.com
  resources:
  - misconfcontrollers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - misconf.controller.anaisurl.com
  resources:
  - misconfcontrollers/status
  verbs:
  - get
